# Generated by Django 5.2 on 2025-05-08 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagepersonnaliser', models.ImageField(upload_to='users')),
                ('name', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField(max_length=9)),
                ('password', models.CharField(max_length=50)),
                ('statutprofessionnel', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('situationfamiliale', models.CharField(max_length=50)),
                ('revenueannuel', models.IntegerField()),
                ('objectiffinanciaire', models.TextField()),
                ('commentaire', models.TextField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
