# Generated by Django 5.2.1 on 2025-05-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofil_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='imagepersonnaliser',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
