# Generated by Django 5.2.1 on 2025-05-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofil_imagepersonnaliser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
