# Generated by Django 5.2.1 on 2025-05-24 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofil_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofil',
            name='situationfamiliale',
        ),
        migrations.RemoveField(
            model_name='userprofil',
            name='ville',
        ),
    ]
