# Generated by Django 5.2.1 on 2025-05-26 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofil_situationfamiliale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='date_heure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
