# Generated by Django 5.2 on 2025-05-14 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('montantcible', models.IntegerField()),
                ('montantactuel', models.IntegerField()),
                ('datelimite', models.DateField()),
                ('datemodification', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('priorite', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Analytic',
        ),
    ]
