# Generated by Django 5.2.1 on 2025-05-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0002_objectif_delete_analytic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectif',
            name='priorite',
        ),
        migrations.AddField(
            model_name='objectif',
            name='categorie',
            field=models.CharField(choices=[('Epargnes', 'Epargnes'), ('Depenses', 'Depenses'), ('Dette', 'Dette')], default='', max_length=50),
        ),
    ]
