# Generated by Django 5.2 on 2025-05-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydepense',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='categoryrevenue',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
