# Generated by Django 5.2 on 2025-05-07 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('description', models.TextField()),
                ('datedepense', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('datemodification', models.DateField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorydepense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('description', models.TextField()),
                ('daterevenue', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('datemodification', models.DateField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categoryrevenue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
