# Generated by Django 5.2.1 on 2025-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_depense_date_alter_depense_datemodification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='datemodification',
            field=models.DateField(auto_now=True),
        ),
    ]
